version: '3.8' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    depends_on:
      - express

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    environment:
      - MONGO_DB_DATABASE=mean-docker
    ports:
      - "3000:3000" #specify ports forewarding
    depends_on:
      - database
    links:
      - database

  database: # name of the third service
    image: mongo:latest # specify image to build container from
    container_name: mean_mongo
    environment: # name of the environment
        - MONGO_DB=mean-docker
    volumes:
        - ./mongo:/home/mongodb
        - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
        - ./mongo/db:/data/db
    ports:
        - "27017:27017" # specify port forewarding
  
