
FROM mongo

WORKDIR /usr/src/db

#COPY movies.json .

# COPY movies.json /movies.json
# COPY init-db.d /docker-entrypoint-initdb.d

#CMD mongoimport --jsonArray --host db --db mean-docker --port 27017 --collection movies
